# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f5f33e5730748e4bf2c2f4b732fee3cc0225b7f2ac5d8860cff6e5355d8aaa5537ff98ec96c318b4760c9bbc6c771eba0cc386fac7fd03d7e0da6b2cebf7e06

test:
  secret_key_base: 24895c947f134101b07bfd2e903fad4fd12e0a9ffa15ae035bcf079826aeeb05e8bd9ed9eff19822f67f3de236a8ffb6a82de3473ad426083cdb7ae6df16e235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
